### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/Excel-Add-in-Bind-To-Table#2]
The [`README`](https://github.com/OfficeDev/Excel-Add-in-Bind-To-Table/blob/master/README.md) makes mention of two project files which seem to be absent from the project codebase.
- `AppManifest.xml`
- `Book1.xlsx`

**Comment by Rick-Kirkham** [comment]
Those were both typos in the Readme. I've fixed it.
